name: Generate Custom Snake
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: output
          
      - uses: Platane/snk@v3.2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=#E52521&color_dots=#FBD000,#22B14C,#00A2E8,#ED1C24,#A349A4
          snake_color: "#E52521"
          snake_pattern: |
            ["..........",
             ".X...X....",
             "..X.X.....",
             "...X......",
             "..X.X.....",
             ".X...X....",
             "..........",
             "..........",
             "..XXXXX...",
             "..X...X..."]
      
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push

      - uses: actions/upload-artifact@v4
        with:
          name: snake-graphics
          path: dist
